dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.0

compiler: # instructing the compiler b how to interpret @chainlin
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.0'

dotenv: .env

networks:
  sepolia:
    eth_usd_price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"

wallets:
  from_key: ${PRIVATE_KEY}